---
.rubocop.yml:
  selected_profile: strict
  default_configs: &default_configs
    AllCops:
      DisplayCopNames: true
      TargetRubyVersion: '2.1'
      Include:
        - "./**/*.rb"
      Exclude:
        - Vagrantfile
    Style/UnneededPercentQ:
      Enabled: false

.gitlab-ci.yml:
  delete: true

.rubocop_todo.yml:
  delete: true

.travis.yml:
  bundler_args: ""
  docker_sets:
    - set: docker/ubuntu-18.04
    - set: docker/ubuntu-16.04
    - set: docker/ubuntu-14.04
#    - set: docker/debian-9
#    - set: docker/debian-8
    - set: docker/centos-7
  docker_defaults:

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw

spec/spec.opts:
  delete: true

spec/spec_helper_local.rb:
  delete: true

.project:
  delete: true

locales/config.yaml:
  copyright_holder: 'Rehan Mahmood'
  comments_tag: 'TRANSLATOR'
  bugs_address: 'https://github.com/rehanone'
  default_locale: 'en'
  source_files:
    - './lib/**/*.rb'

spec/acceptance/nodesets/centos-7-x64.yml:
spec/acceptance/nodesets/debian-8-x64.yml:
spec/acceptance/nodesets/debian-9-x64.yml:
spec/acceptance/nodesets/default.yml:
spec/acceptance/nodesets/docker/centos-7.yml:
spec/acceptance/nodesets/docker/debian-8.yml:
spec/acceptance/nodesets/docker/debian-9.yml:
spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
spec/acceptance/nodesets/docker/ubuntu-16.04.yml:
spec/acceptance/nodesets/docker/ubuntu-18.04.yml:
